#ifndef TEST_PARAMS_H_INCLUDED
#define TEST_PARAMS_H_INCLUDED

#define NUM_ELEMS 10
#define INC_VALUE 1

#define RANGE_ELEMS_S1_LOW 0
#define RANGE_ELEMS_S1_HIGH 9

#define RANGE_ELEMS_S2_LOW 10
#define RANGE_ELEMS_S2_HIGH 19

#define RANGE_ELEMS_S3_LOW 20
#define RANGE_ELEMS_S3_HIGH 29

#define NUM_RESIZE_AMOUNT 10
#endif